# -*- coding: utf-8 -*-
"""시각화 과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2BG5LU6CTEhK2P4fuAQ92KwmSQGu2-p
"""

import matplotlib.pylab as plt
import csv
import random

label = []
value = []
colors = []

#파일 읽어오기
with open('f.csv', 'r', encoding='ISO-8859-1') as f:
    data = csv.reader(f)


    for i, row in enumerate(data):
        if 68 <= i <= 78: #데이터 행
            label.append(row[0])
            value.append(row[1])

#문자열 리스트인 value[]에서 ','을 제외하고 정수로 변환
value = list(map(int, [v.replace(',', '') for v in value]))

#6진수로 색 랜덤 생성
for _ in range(len(label)):
  colors.append('#%06x' % random.randint(0,0xFFFFFF))

#print(label)
#print(value)

plt.title('2024 Popular Social Media', fontweight = 'bold')
plt.pie(value, labels = label, colors = colors)
plt.legend(loc = 'center', bbox_to_anchor=(0.5, -0.3))
#bbox_to_anchor 범례 위치 x, y

plt.show()

import matplotlib.pylab as plt
import csv
import seaborn as sns

label = []
value = []

#파일 읽어오기
with open('f.csv', 'r', encoding='ISO-8859-1') as f:
    data = csv.reader(f)


    for i, row in enumerate(data):
        if 68 <= i <= 78: #데이터 행
            label.append(row[0])
            value.append(row[1])

#문자열 리스트인 value[]에서 ','을 제외하고 정수로 변환
value = list(map(int, [v.replace(',', '') for v in value]))

print(label)
print(value)

#색상 메소드
c = sns.color_palette("husl", n_colors=15)

plt.figure(figsize=(5, 5))  # 크기 조절

plt.title('2024 Popular Social Media', fontweight = 'bold')
plt.pie(value, labels = label, colors = c)
plt.legend(loc = 'center', bbox_to_anchor=(0.5, -0.34))
#bbox_to_anchor 범례 위치 x, y

plt.show()

import matplotlib.pyplot as plt

# 데이터 생성
ages = ['Teens', '20s', '30s', '40s', '50s', '60s']
platforms = ['Instagram', 'Facebook', 'YouTube']
ratios = {
    'Teens': [3, 4, 2],
    '20s': [2, 3, 4],
    '30s': [3, 3, 3],
    '40s': [3, 3, 3],
    '50s': [3, 4, 3],
    '60s': [3, 3, 4]
}
average_time = [6, 5, 5, 5, 5, 5]

# 막대 그래프 그리기
plt.figure(figsize=(10, 6))

# 플랫폼 사용 비율 막대 그래프
bar_width = 0.2
index = range(len(ages))
colors = ['skyblue', 'lightgreen', 'salmon']

for i, platform in enumerate(platforms):
    plt.bar([x + i * bar_width for x in index],
            [ratios[age][i] for age in ages],
            bar_width,
            label=platform,
            color=colors[i])

plt.xlabel('Age')
plt.ylabel('Ratio of Usage')
plt.title('Platform Usage Ratio by Age')
plt.xticks([x + bar_width for x in index], ages)
plt.legend()

# 연령별 평균 사용시간 가로 막대 그래프
plt.figure(figsize=(10, 6))
plt.barh(ages, average_time, color='lightblue')
plt.xlabel('Average Time Spent')
plt.ylabel('Age')
plt.title('Average Time Spent by Age')

plt.tight_layout()
plt.show()